export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  UNAUTHORIZED_LOGIN = "UNAUTHORIZED_LOGIN",
  UNAUTHORIZED_REFRESH_TOKEN = "UNAUTHORIZED_REFRESH_TOKEN",
  FORBIDDEN_EMAIL_NOT_VERIFIED = "FORBIDDEN_EMAIL_NOT_VERIFIED",
  FORBIDDEN_INVALID_UNIVERSITY_EMAIL = "FORBIDDEN_INVALID_UNIVERSITY_EMAIL",
  FORBIDDEN_INVALID_USERNAME = "FORBIDDEN_INVALID_USERNAME",
  FORBIDDEN_INVALID_USER = "FORBIDDEN_INVALID_USER",
  FORBIDDEN_INVALID_EMAIL_TOKEN = "FORBIDDEN_INVALID_EMAIL_TOKEN",
}
