export const localStorageKeys = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  USERNAME: "USERNAME",
  USER_AVATAR: "USER_AVATAR",
  USER_ID: "USER_ID",
  EMAIL_ADDRESS: "EMAIL_ADDRESS",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  USER_FULLNAME: "USER_FULLNAME",
  USER_STATUS: "USER_STATUS",
  USER_SEARCH_CAMPUS: "USER_SEARCH_CAMPUS",
};

export const sessionStorageKeys = {
  EMAIL_ADDRESS: "EMAIL_ADDRESS"
}