export const localStorageKeys = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  USERNAME: "USERNAME",
  USER_AVATAR: "USER_AVATAR",
  USER_ID: "USER_ID",
  EMAIL_ADDRESS: "EMAIL_ADDRESS",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  USER_FULLNAME: "USER_FULLNAME",
  USER_STATUS: "USER_STATUS",
  USER_SEARCH_CAMPUS_LOCATION: "USER_SEARCH_CAMPUS_LOCATION",
  USER_SEARCH_UNIVERSITY: "USER_SEARCH_UNIVERSITY",
  USER_UNIVERSITY_ID: "USER_UNIVERSITY_ID",
  USER_CAMPUS_ID: "USER_CAMPUS_ID",
  DEFAULT_PICKUP_LOCATION_ID: "DEFAULT_PICKUP_LOCATION_ID",
};

export const sessionStorageKeys = {
  EMAIL_ADDRESS: "EMAIL_ADDRESS"
}